name: CD

on:
  push:
    branches:
      - ci-cd

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ci-cd
          persist-credentials: false
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: npm run build
      - name: Commit files
        run: |
          git config --local user.email "action@github.com" 
          git config --local user.name "Github Action"
          git config --local pull.rebase true
          git commit -m ":rocket: deploy compiled files" -a || echo
      - name: Update dist on master
        run: |
          git checkout master
          git merge ci-cd
          git commit -m ":octopus: rebase dist from ci-cd branch" || echo
      - uses: ad-m/github-push-action@master
        with:
          branch: master
          github_token: ${{ secrets.ACCESS_TOKEN }}
