name: CI

on: pull request

jobs:
  integrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ci-cd
      -  uses: actions/setup-node@v1
          with:
            node-version: 12
      - run: npm ci
      - run: npm test
      - run: npm run build
