name: Sungka

on:
  issues:
    types: [opened]

jobs:
  move:
    runs-on: ubuntu-latest
    if: startsWith(github.event.issue.title, 'sungka|')
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - run: |
          git pull origin master
      - name: Make a move
        uses: ./move
        id: move
        with:
          title: ${{ github.event.issue.title }}
          user: ${{ github.event.issue.user.login }}
      - name: Commit files
        run: |
          git config --local user.email "action@github.com" 
          git commit -m user.name "Github Action"
          git commit -m "Update board" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
      - uses: peter-evans/close-issue@v1
        with:
          issue-number: ${{ github.event.issue.number }}
