name: Sungka

on:
  issues:
    types: [opened]

jobs:
  move:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    if: startsWith(github.event.issue.title, 'sungka|')
    steps:
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
      run: npm run build
