name: Sungka

on:
  issues:
    types: [opened]

jobs:
  move:
    runs-on: ubuntu-latest
    if: startsWith(github.event.issue.title, 'sungka|')
    steps:
      - name: Check out repo
        uses: actions/checkout@v2.3.1
      - name: Set env vars
        run: |
          echo ::set-env name=TERM::xterm
          echo ::set-env name=REPOSITORY::${{ github.repository }}
          echo ::set-env name=EVENT_ISSUE_NUMBER::${{ github.event.issue.number }}
          echo ::set-env name=EVENT_USER_LOGIN::${{ github.event.issue.user.login }}
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm install
      - name: Compile Typescript
        run: npm run build
      - name: Make a move
        run: node move/dist/main.js "${{ github.event.issue.title }}"
      - name: Commit files
        run: |
          git config --local user.email "action@github.com" 
          git config --local user.name "Github Action"
          git commit -m ":robot: update board" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
      - uses: peter-evans/close-issue@v1
        with:
          issue-number: ${{ github.event.issue.number }}
